@echo off
cd /d "%~dp0"
echo ============================================
echo   SWITCH THE WEBSITE TO THE FAKE BACKEND
echo ============================================
echo.

> ".env.local" echo # Auto-generated by use-mock-backend.bat
>>".env.local" echo # This points the website at the LOCAL fake backend.
>>".env.local" echo # Delete this file (or run use-real-backend.bat) to go back to the real site.
>>".env.local" echo VITE_BACKEND_BASE_URL=http://localhost:5000

echo [OK] The website will now use the FAKE backend (http://localhost:5000).
echo.
echo NEXT, two things:
echo   1) Make sure the fake backend is running - start-mock-backend.bat
echo   2) RESTART the website so it picks up the change:
echo        - close the window running "npm run dev"
echo        - run  npm run dev  again  (or your start-website file)
echo.
echo Then log in at http://localhost:3000/login with ANY password:
echo        admin@test.com    for the Admin dashboard
echo        teacher@test.com  for the Teacher dashboard
echo        student@test.com  for the Student dashboard
echo.
pause
